name: ai-meta-blog
services:
  - name: web
    github:
      repo: brendendiaz111/ai-meta-blog
      branch: main
    build_command: "pip install -r requirements.txt"
    run_command: "gunicorn app:app"
    envs:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: OPENAI_API_KEY
        value: "${OPENAI_API_KEY}"
    http_port: 8000
